# Generated by Django 3.1.3 on 2020-11-26 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Github',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.CharField(max_length=99)),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('javascript', models.IntegerField()),
                ('java', models.IntegerField()),
                ('python', models.IntegerField()),
                ('php', models.IntegerField()),
                ('type', models.CharField(max_length=20)),
                ('github', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='api.github')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Programming',
        ),
        migrations.AlterModelOptions(
            name='fileandfolder',
            options={'ordering': ['-created_at', '-updated_at']},
        ),
        migrations.AddField(
            model_name='fileandfolder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fileandfolder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
