# Generated by Django 3.1.3 on 2020-11-26 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201126_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.IntegerField()),
                ('folder', models.IntegerField()),
                ('github', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='api.github')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Folder',
        ),
    ]
