# Generated by Django 3.1.3 on 2020-12-01 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_github'),
        ('api', '0004_auto_20201126_0819'),
    ]

    operations = [
    ]
